// Mirror package.json's version into a JS module that the browser can import.
// Run: npm run build:version

import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const pkg = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8'));
const out = `// Generated by scripts/build-version.mjs — do not edit by hand.
export const APP_VERSION = ${JSON.stringify(pkg.version)};
`;
writeFileSync(path.join(root, 'public', 'js', 'version.js'), out);
console.log('wrote public/js/version.js with version', pkg.version);
